# Generated by Django 2.0.9 on 2019-02-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_discount',
            field=models.FloatField(verbose_name='desconto'),
        ),
    ]
