# Generated by Django 2.0.9 on 2019-03-10 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(default='6627017', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 15, 7, 47, 850454), verbose_name='Data de Vencimento'),
        ),
    ]
