# Generated by Django 2.0.9 on 2019-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('1', 'activo'), ('2', 'desactivo')], help_text='status', max_length=254),
        ),
    ]
