# Generated by Django 2.0.9 on 2019-03-10 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20190310_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(default='5979801', unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 15, 14, 47, 781817), verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Pacote'),
        ),
    ]
