# Generated by Django 2.0.9 on 2019-03-10 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20190310_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(default='4268825', unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='plan',
            field=models.CharField(choices=[('1', 'Mensal'), ('2', 'Semanal')], help_text='Plano', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 18, 34, 35, 905355), verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Plan'),
        ),
    ]
