# Generated by Django 2.0.9 on 2019-02-27 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_auto_20190224_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(max_length=9, unique=True, validators=[django.core.validators.MinLengthValidator(7, 'codigo com 9 digitos'), django.core.validators.MinLengthValidator(7, 'codigo com 9 digitos')]),
        ),
    ]
