# Generated by Django 2.0.9 on 2019-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20190227_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(verbose_name='914871'),
        ),
    ]
