# Generated by Django 2.0.9 on 2019-03-10 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_auto_20190310_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='plan',
            new_name='payment_plan',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicant_id',
            field=models.IntegerField(default='7973708', unique=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.CharField(choices=[('1', 'activo'), ('2', 'desactivo')], default='1', help_text='status', max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 19, 21, 19, 369779), verbose_name='Data de Vencimento'),
        ),
    ]
